default: &default
  adapter: postgresql
  host: localhost
  username: <%= ENV['USER'] %>

development:
  <<: *default
  database: nihongo-up-development

test:
  <<: *default
  database: nihongo-up-test

production:
  <<: *default
  database: nihongo-up-production
